# Generated by Django 5.2.4 on 2025-07-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='irr_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='packaged_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='packaged_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
