# Generated by Django 5.2.4 on 2025-07-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublot',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
