# Generated by Django 5.2.4 on 2025-07-19 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_sublot_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='last_sync_time',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='notes',
        ),
        migrations.AddField(
            model_name='synclog',
            name='board_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
