# Generated by Django 5.2.4 on 2025-07-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_lot_irr_out_date_lot_packaged_by_lot_packaged_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='data_source',
            field=models.CharField(choices=[('PRIMARY_SYNC', 'Primary Sync'), ('PLACEHOLDER', 'Placeholder')], default='PRIMARY_SYNC', max_length=20),
        ),
    ]
