# Generated by Django 4.2.23 on 2025-07-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_synclog_last_sync_time_remove_synclog_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(help_text='The ID of the Monday.com board.', max_length=20, unique=True)),
                ('name', models.CharField(help_text="e.g., 'Labeling - July 2025'", max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
