# Generated by Django 4.2.23 on 2025-08-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_monthlyboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublot',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
