# Generated by Django 4.2.23 on 2025-08-03 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_sublot_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublot',
            name='source_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_lots', to='tracker.monthlyboard'),
        ),
    ]
