# Generated by Django 4.2.23 on 2025-08-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_sublot_source_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublot',
            name='latest_comment',
            field=models.TextField(blank=True, help_text='Stores the latest update/comment from Monday.com for this item.', null=True),
        ),
    ]
