# Generated by Django 4.2.23 on 2025-08-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_sublot_latest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='graft_id_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='sterilization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
