# Generated by Django 4.2.23 on 2025-08-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_lot_graft_id_number_lot_product_code_lot_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='da_val',
            field=models.BooleanField(default=False, help_text="Represents the 'DA / VAL' checkbox"),
        ),
        migrations.AddField(
            model_name='lot',
            name='fpp_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='irr_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='irr_run_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='qc_out_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='qc_out_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
