# Generated by Django 4.2.23 on 2025-08-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_lot_da_val_lot_fpp_by_lot_irr_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublot',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sublot',
            name='days_to_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sublot',
            name='days_to_release',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sublot',
            name='initial_quantity',
            field=models.IntegerField(blank=True, help_text="Corresponds to the 'QTY' column", null=True),
        ),
        migrations.AddField(
            model_name='sublot',
            name='labeling_progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sublot',
            name='labeling_status',
            field=models.CharField(blank=True, help_text="Corresponds to the 'Labeling' status", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sublot',
            name='product_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sublot',
            name='qc_status',
            field=models.CharField(blank=True, help_text="Corresponds to the 'QC' status", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sublot',
            name='due_date',
            field=models.DateField(blank=True, help_text="Corresponds to 'Release Date'", null=True),
        ),
        migrations.AlterField(
            model_name='sublot',
            name='status',
            field=models.CharField(blank=True, help_text="Corresponds to 'Chart Status'", max_length=100, null=True),
        ),
    ]
